version: "3"
services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - /tmp/wso2-pg-data:/var/lib/postgresql/data

#  wso2:
#    build: .
#    ports:
#      - 9443:9443
