version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew build

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .

      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o ~/app.tar app

      - save_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/app.tar
            - ~/.gradle

      - run:
          name: Push Docker image
          command: |
            BRANCH_TAG=`echo ${CIRCLE_BRANCH} | sed 's/\//-/g'`
            docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}"
            docker tag app "cshr/wso2-is:${BRANCH_TAG}"
            docker push "cshr/wso2-is:${BRANCH_TAG}"
            docker tag app "cshr/wso2-is:${CIRCLE_SHA1}"
            docker push "cshr/wso2-is:${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
