#! /usr/bin/env bash

docker build -t cshr/lpg-wso2-is:$TRAVIS_COMMIT .
docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
docker push cshr/lpg-wso2-is

echo ${TRAVIS_COMMIT}
sudo pip install ansible
./environ/deploy dev ${TRAVIS_COMMIT}

# cd test/headless
# npm install
