#! /usr/bin/env bash

echo "Building lpg-wso2-is:${TRAVIS_COMMIT}"

./gradlew build
docker build -t cshr/lpg-wso2-is:$TRAVIS_COMMIT .
docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
docker push cshr/lpg-wso2-is:$TRAVIS_COMMIT

export PATH="`pwd`/pyhome/bin:${PATH}"
export PYTHONPATH="`pwd`/pyhome/lib/python/site-packages:${PYTHONPATH}"
export PYTHONPATH="`pwd`/pyhome/lib/python2.7/site-packages:${PYTHONPATH}"

PYTHONUSERBASE=pyhome pip install --user ansible==2.4.3.0
