#!/usr/bin/env bash

repoName=lpg-ansible-mvp

cd "$(dirname "$0")"

if [ -d $repoName ]; then
    cd ${repoName}
    git clean -f
    git config advice.detachedHead false
    git reset --hard HEAD
    git remote update
    git checkout origin/master
    echo "----- `pwd`"
else
    git clone https://github.com/Civil-Service-Human-Resources/lpg-ansible-mvp
    git config advice.detachedHead false
    cd ${repoName}
    echo "----- `pwd` -----"
fi

./deploy.sh wso2is "$1" "$2"  || exit 2